import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer"
import { ClerkProvider } from "@clerk/nextjs";
import { DM_Mono } from "next/font/google";
import ReduxProvider from "@/components/ReduxProvider";
const dmMono = DM_Mono({ subsets: ["latin"], weight: ["400", "500"] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >

        <body className="min-h-full flex flex-col">
          <ReduxProvider>        
            <Navbar />
            <main>{children}</main>
            <Footer />
          </ReduxProvider>
        </body>

      </html>
    </ClerkProvider>
  );
}
